apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::459980208220:role/eksctl-roboshop-devn-nodegroup-rob-NodeInstanceRole-oSHj4hcSC86z
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::459980208220:user/suresh
      username: suresh 
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::459980208220:user/ramesh
      username: ramesh  
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-07T12:04:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1141"
  uid: e9f00f02-f900-4957-8fee-6026532631ba
